# Generated by Django 3.2.9 on 2021-11-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='номер владельца')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('progress', 'Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='created', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='владелец', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='категории')),
            ],
            options={
                'verbose_name': 'категоория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='одежда')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена')),
                ('count', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='категории', to='shop.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='размер', to='shop.size')),
            ],
            options={
                'verbose_name_plural': 'одежда',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
